package controller.request;

public enum RequestType {
    NULL,
    INVALID,
    SHOW_MENU,
    HELP,
    SHOW,
    BACK,

    CREATE_ACCOUNT,
    LOGIN,
    SHOW_LEADERBOARD,
    SAVE,
    LOGOUT,
    HESOYAM,

    MAIN_MENU,
    COLLECTION,
    SHOP,
    BATTLE,
    EXIT,

    SHOW_COLLECTION,
    SEARCH,
    SEARCH_COLLECTION,
    BUY,
    SELL,

    CREATE_DECK,
    DELETE_DECK,
    ADD_TO_DECK,
    REMOVE_FROM_DECK,
    VALIDATE_DECK,
    SELECT_DECK,
    SHOW_ALL_DECKS,
    SHOW_DECK,

    GAME_INFO,
    SHOW_MY_MINIONS,
    SHOW_OPPONENT_MINIONS,
    SHOW_CARD_INFO,
    SELECT,
    MOVE_TO,
    ATTACK,
    ATTACK_COMBO,
    USE_SPECIAL_POWER,
    SHOW_HAND,
    INSERT_IN,
    END_TURN,
    SHOW_COLLECTABLES,
    SHOW_INFO,
    USE,
    SHOW_NEXT_CARD,
    ENTER_GRAVEYARD,
    END_GAME,
    SHOW_CARDS,
    SHOW_BATTLEFIELD,
    KILL,
    MP,

    //  ALL COMMANDS
}


// HANDLE SIMILAR TYPES FOR DIFFERENT CLASSES