package view;

public enum Message {
    NO_CARD_IS_SELECTED("NO CARD IS SELECTED"),
    USERNAME_IS_TAKEN("USERNAME ALREADY TAKEN"),
    CARD_IS_NOT_IN_COLLECTION("NO CARD OR ITEM WITH THIS NAME IS AVAILABLE"),
    CARD_IS_NOT_IN_DECK("CARD IS NOT IN DECK"),
    DECK_IS_NOT_VALID("DECK IS NOT VALID"),
    INVALID_MOVE_TARGET("MOVE TARGET IS NOT VALID"),
    INVALID_CARD_ID("NO CARD WITH SUCH ID"),
    HAVE_NOT_MANA("NOT ENOUGH MANA"),
    YOU_MUST_LOG_IN("YOU MUST LOGIN"),
    LOGIN_FAILED("LOGIN FAILED"),
    INVALID_USERNAME("INVALID USERNAME"),
    NO_CARD_WITH_THIS_NAME("NO CARD WITH THIS NAME"),
    DECK_ALREADY_EXISTS("A DECK WITH THIS NAME ALREADY EXISTS"),
    NO_SUCH_DECK("NO DECK WITH THIS NAME"),
    ALREADY_IN_DECK("CARD IS ALREADY IN DECK"),
    DECK_IS_FULL("DECK IS FULL. YOU CANNOT ADD MORE CARDS"),
    DECK_HAS_HERO("DECK ALREADY HAS A HERO"),
    DECK_HAS_ITEM("DECK ALREADY HAS A ITEM"),
    DECK_CANNOT_BE_MAIN("DECK IS NOT COMPLETED AND CANNOT BE CHOSEN AS MAIN DECK"),
    ADDED_SUCCESSFULLY("ADDED SUCCESSFULLY"),
    HERO_IS_USED_IN_A_DECK("THIS HERO IS USED IN ANOTHER DECK"),
    DELETED_SUCCESSFULLY("DELETED SUCCESSFULLY"),
    YOU_MUST_LOGOUT("YOU MUST LOGOUT"),
    AIPLAYER_IS_NULL("AIPLAYER IS NULL"),
    UNAVAILABLE_FOR_ATTACK("OPPONENT MINION IS UNAVAILABLE FOR ATTACK"),
    ATTACKER_CANT_MOVE("ATTACKER CANNOT MOVE"),
    INVALID_CELL("CELL IS INVALID."),
    SELECTED_CARD_NOT_MINION("SELECTED CARD MUST BE MINION"),
    NOT_COMBO("SELECTED MINION IS NOT COMBO"),
    NO_ATTACKER_SELECTED("YOU MUST SELECT ATTACKER"),
    HASNT_SPECIAL("THIS CARD HAS NO SPECIAL POWER"),
    NO_COLLECTABLE_SELECTED("NO COLLECTABLE IS SELECTED"),
    COOLDOWN("HERO IS IN COOLDOWN"),
    NO_SPELL_SELECTED("YOU MUST CHOOSE A SPELL"),
    STUNNED("ATTACKER IS STUNNED"),
    PASSWORD_EMPTY("PASSWORD IS EMPTY"),
    NO_SUCH_USER("NO SUCH USER"),
    ;

    private String message;

    public String getMessage() {
        return message;
    }

    Message(String message) {
        this.message = message;
    }
}
